version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
      - VIRTUAL_HOST=${DOMAIN:-}
      - LETSENCRYPT_HOST=${DOMAIN:-}
      - LETSENCRYPT_EMAIL=${EMAIL:-}
      - LETSENCRYPT_TEST=${DEBUG:-false}
    ports:
      - 1337:1337
    volumes:
      - ./app:/usr/src/api/strapi-app
      - ./schema:/usr/src/api/schema
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - /data/db
      - ./import:/data/import
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
