version: '3'

services:
  strapi:
    container_name: strapi
    image: vitruviantech/strapi:${VERSION:-3.0.0-beta.19.3}
    environment:
      - VERSION=${VERSION:-3.0.0-beta.19.3}
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    volumes:
      - /srv/app
      - ./schema:/srv/schema
    depends_on:
      - db
    restart: unless-stopped
    networks:
      net:
        aliases:
          - strapi_app

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - /data/db
      - ./import:/data/import
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      net:
        aliases:
          - strapi_db

networks:
  net:
